# Generated by Django 2.2.14 on 2020-08-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='create_at',
            field=models.DateTimeField(null='True', verbose_name='date published'),
            preserve_default='True',
        ),
    ]
